# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [3]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- Postulamos que los Pokémon de tipo Dragón tienen, en promedio, más estadísticas de HP que Planta. Elija la prueba adecuada y, con un 5% de significancia, comente sus hallazgos.

In [ ]:
# H0 = AVG HP DRAGON <= AVG HP GRASS
# H1 = AVG HP DRAGON > AVG HP GRASS
# ALFA = 0.05

dragon_hp = df[df['Type 1'] == 'Dragon']['HP']
grass_hp = df[df['Type 1'] == 'Grass']['HP']

_, p_value = st.ttest_ind(dragon_hp, grass_hp, equal_var=False, alternative='greater')
print(p_value)

0.0007993609745420602

In [ ]:
# ya que el p_value es mucho menor a alfa, se rechaza la hipotesis nula, por lo tanto podemos decir que hay evidencia estadistica que los pokemon de tipo dragon tienen, en promedio, mas HP que los de tipo grass.

- Postulamos que los Pokémon legendarios tienen estadísticas diferentes (HP, Ataque, Defensa, Sp.Atk, Sp.Def, Velocidad) en comparación con los no legendarios. Elija la prueba adecuada y, con un 5% de significancia, comente sus hallazgos.

In [ ]:
# H0 = legendary estadisticas = no legendary estadisticas
# H1 = legendary estadisticas != no legendary estadisticas
# ALFA = 0.05

legendary = df[df['Legendary'] == True]
no_legendary = df[df['Legendary'] == False]

stats_col = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

_, p_value = st.ttest_ind(legendary[stats_col], no_legendary[stats_col], equal_var=False, alternative='two-sided')
print(p_value)

[1.00269117e-13 2.52037245e-16 4.82699849e-11 1.55146141e-21
 2.29493279e-15 1.04901631e-18]

In [ ]:
# ya que los 6 p_values son inferiores a 0.05, rechazamos la hipotesis nula en todas las estadisticas.
#los pokemones legendarios tienen estadisticas significativamente diferentes a los NO legendarios

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

**Suponemos que las casas cercanas a una escuela o a un hospital son más caras.**

- Coordenadas escolares (-118, 34)
- Coordenadas del hospital (-122, 37)

Consideramos que una casa (barrio) está cerca de una escuela u hospital si la distancia es inferior a 0,50.

Pista:
1. Escribe una función para calcular la distancia euclidiana desde cada casa (barrio) hasta la escuela y el hospital.
2. Divida su conjunto de datos en casas cercanas y alejadas de un hospital o escuela.
3. Elija la prueba adecuada y, con un 5% de significancia, comente sus hallazgos.

In [5]:
# Coordenadas escolares (-118, 34)
# Coordenadas del hospital (-122, 37)

def distancia_euclidiana(x1, y1, x2, y2):
    return np.sqrt((x1 - x2)**2 + (y1 - y2)**2)

df['dist_school'] = distancia_euclidiana(df['longitude'], df['latitude'], -118, 34)
df['dist_hospital'] = distancia_euclidiana(df['longitude'], df['latitude'], -122, 37)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_school,dist_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508

In [7]:
cerca = df[(df['dist_school']< 0.50) | (df['dist_hospital']< 0.50)]
lejos = df[(df['dist_school'] >= 0.50) & (df['dist_hospital'] >= 0.50)]

print("Casas cerca:", len(cerca))
print("Casas lejos:", len(lejos))

Casas cerca: 6829
Casas lejos: 10171

In [8]:
#H0: precio medio de casas cerca <= precio medio casas lejos
#H1: precio medio de casas cerca > precio medio casas lejos
# alfa = 0.05

_, p_value = st.ttest_ind(cerca["median_house_value"], lejos["median_house_value"],equal_var=False, alternative="greater")
print(p_value)

1.5032478884295899e-301

In [ ]:
#el p_value, es prácticamente cero, muy inferior a 0.05,  por lo que rechazamos la hipotesis nula.
# las casas cercanas a una escuela o a un hospital son, en promedio, significativamente más caras que las que estan lejos.